## Import Important Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import  StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report , roc_auc_score , f1_score , precision_score , recall_score , mean_squared_error , r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from imblearn.over_sampling import SMOTE
import joblib
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV

## Read The Data and Preprocess it

In [2]:
crop = pd.read_csv(r'C:\Users\Hamada\Downloads\archive (14)\Crop_recommendation.csv')
crop.head(5)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [4]:
crop.duplicated().sum()

0

In [5]:
crop.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
crop.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [7]:
crop['label'].value_counts()

label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

## Encode the Label Column to Number to be easy to Predict

In [8]:
crop['label'] = LabelEncoder().fit_transform(crop['label'])

In [9]:
crop.head(5)

    N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536     20
1  85  58  41    21.770462  80.319644  7.038096  226.655537     20
2  60  55  44    23.004459  82.320763  7.840207  263.964248     20
3  74  35  40    26.491096  80.158363  6.980401  242.864034     20
4  78  42  42    20.130175  81.604873  7.628473  262.717340     20

In [10]:
crop['label'].value_counts()

label
20    100
11    100
8     100
6     100
4     100
17    100
16    100
0     100
15    100
21    100
7     100
12    100
1     100
19    100
10    100
2     100
14    100
13    100
18    100
9     100
3     100
5     100
Name: count, dtype: int64

## Let's Start with Splitting data in x , y

In [11]:
x = crop.drop('label',axis=1)
y = crop['label']

In [12]:
y.value_counts(normalize=True)

label
20    0.045455
11    0.045455
8     0.045455
6     0.045455
4     0.045455
17    0.045455
16    0.045455
0     0.045455
15    0.045455
21    0.045455
7     0.045455
12    0.045455
1     0.045455
19    0.045455
10    0.045455
2     0.045455
14    0.045455
13    0.045455
18    0.045455
9     0.045455
3     0.045455
5     0.045455
Name: proportion, dtype: float64

## Splitted it into train and test

In [13]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [14]:
x_tr , x_val , y_tr , y_val = train_test_split(x_train,y_train,test_size=0.2)

In [15]:
std = StandardScaler()

x_tr = std.fit_transform(x_tr)
x_val = std.transform(x_val)
x_test = std.transform(x_test)

## Let's Try all Models and we will Decide which is The Best

In [16]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(x_tr,y_tr)
dt.score(x_val,y_val)

0.9914772727272727

In [17]:
print(classification_report(y_val,dt.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00        16
           6       1.00      1.00      1.00        17
           7       1.00      1.00      1.00        16
           8       0.91      1.00      0.95        21
           9       1.00      1.00      1.00        15
          10       0.90      1.00      0.95         9
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        15
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        18
          18       1.00      1.00      1.00        17
          19       1.00      1.00      1.00        15
          20       1.00      0.88      0.94        17
          21       1.00      1.00      1.00        20

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [18]:
rfc = RandomForestClassifier()
rfc.fit(x_tr,y_tr)
rfc.score(x_val,y_val)

0.9886363636363636

In [19]:
print(classification_report(y_val,rfc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00        16
           6       1.00      1.00      1.00        17
           7       1.00      1.00      1.00        16
           8       0.88      1.00      0.93        21
           9       1.00      1.00      1.00        15
          10       0.90      1.00      0.95         9
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        15
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        18
          18       1.00      1.00      1.00        17
          19       1.00      1.00      1.00        15
          20       1.00      0.82      0.90        17
          21       1.00      1.00      1.00        20

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [20]:
lin_svc = SVC(kernel='linear')
lin_svc.fit(x_tr,y_tr)
lin_svc.score(x_val,y_val)

0.9744318181818182

In [21]:
print(classification_report(y_val,lin_svc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      0.94      0.97        16
           6       0.94      1.00      0.97        17
           7       1.00      1.00      1.00        16
           8       0.80      0.95      0.87        21
           9       0.94      1.00      0.97        15
          10       0.90      1.00      0.95         9
          11       1.00      0.95      0.98        21
          12       1.00      1.00      1.00        15
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        18
          18       1.00      0.94      0.97        17
          19       1.00      1.00      1.00        15
          20       0.93      0.76      0.84        17
          21       1.00      1.00      1.00        20

    accuracy                           0.97       352
   macro avg       0.98      0.98      0.98       352
weighted avg       0.98      0.97      0.97       352

In [22]:
poly_svc = SVC(kernel='poly')
poly_svc.fit(x_tr,y_tr)
poly_svc.score(x_val,y_val)

0.9176136363636364

In [23]:
print(classification_report(y_val,poly_svc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.92      0.96        13
           2       0.87      0.72      0.79        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      0.88      0.93        16
           6       1.00      1.00      1.00        17
           7       1.00      1.00      1.00        16
           8       0.76      0.90      0.83        21
           9       0.94      1.00      0.97        15
          10       0.89      0.89      0.89         9
          11       0.62      1.00      0.76        21
          12       1.00      1.00      1.00        15
          13       1.00      0.81      0.90        16
          14       0.83      1.00      0.91        20
          15       1.00      1.00      1.00        12
          16       1.00      0.91      0.95        11
          17       1.00      0.67      0.80        18
          18       1.00      0.82      0.90        17
          19       0.94      1.00      0.97        15
          20       0.92      0.71      0.80        17
          21       1.00      1.00      1.00        20

    accuracy                           0.92       352
   macro avg       0.94      0.92      0.93       352
weighted avg       0.93      0.92      0.92       352

In [24]:
poly_svc = SVC(kernel='rbf')
poly_svc.fit(x_tr,y_tr)
poly_svc.score(x_val,y_val)

0.9715909090909091

In [25]:
print(classification_report(y_val,poly_svc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      0.94      0.97        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00        16
           6       0.94      1.00      0.97        17
           7       1.00      1.00      1.00        16
           8       0.80      0.95      0.87        21
           9       1.00      1.00      1.00        15
          10       0.82      1.00      0.90         9
          11       1.00      0.95      0.98        21
          12       1.00      1.00      1.00        15
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      0.94      0.97        18
          18       1.00      1.00      1.00        17
          19       1.00      1.00      1.00        15
          20       0.86      0.71      0.77        17
          21       1.00      1.00      1.00        20

    accuracy                           0.97       352
   macro avg       0.97      0.97      0.97       352
weighted avg       0.97      0.97      0.97       352

In [26]:
naive = GaussianNB()
naive.fit(x_tr,y_tr)
naive.score(x_val,y_val)

0.9943181818181818

In [27]:
print(classification_report(y_val,naive.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00        16
           6       1.00      1.00      1.00        17
           7       1.00      1.00      1.00        16
           8       0.91      1.00      0.95        21
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00         9
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        15
          13       1.00      1.00      1.00        16
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        18
          18       1.00      1.00      1.00        17
          19       1.00      1.00      1.00        15
          20       1.00      0.88      0.94        17
          21       1.00      1.00      1.00        20

    accuracy                           0.99       352
   macro avg       1.00      0.99      1.00       352
weighted avg       0.99      0.99      0.99       352

In [28]:
KNN = KNeighborsClassifier(n_neighbors=20)
KNN.fit(x_tr,y_tr)
KNN.score(x_val,y_val)

0.9289772727272727

In [29]:
print(classification_report(y_val,KNN.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       0.89      0.94      0.92        18
           3       1.00      1.00      1.00        15
           4       0.87      1.00      0.93        13
           5       1.00      0.94      0.97        16
           6       0.94      1.00      0.97        17
           7       1.00      1.00      1.00        16
           8       0.78      1.00      0.88        21
           9       0.94      1.00      0.97        15
          10       0.82      1.00      0.90         9
          11       1.00      0.95      0.98        21
          12       0.79      1.00      0.88        15
          13       1.00      0.69      0.81        16
          14       0.83      1.00      0.91        20
          15       1.00      1.00      1.00        12
          16       1.00      0.64      0.78        11
          17       1.00      0.72      0.84        18
          18       1.00      0.82      0.90        17
          19       0.88      1.00      0.94        15
          20       0.92      0.71      0.80        17
          21       1.00      1.00      1.00        20

    accuracy                           0.93       352
   macro avg       0.94      0.93      0.93       352
weighted avg       0.94      0.93      0.93       352

In [30]:
Log = LogisticRegression()
Log.fit(x_tr,y_tr)
Log.score(x_val,y_val)

0.9573863636363636

In [31]:
print(mean_squared_error(y_val,Log.predict(x_val)))
print(r2_score(y_val,Log.predict(x_val)))

3.3494318181818183
0.9182679118326679

In [32]:
linear = LinearRegression()
linear.fit(x_tr,y_tr)
linear.score(x_val,y_val)

0.30530120470363287

In [33]:
print(mean_squared_error(y_val,linear.predict(x_val)))
print(r2_score(y_val,linear.predict(x_val)))

28.469188799562062
0.30530120470363287

## Hyper Paramater Tuning

In [34]:
RFC_Grid = GridSearchCV(RandomForestClassifier(),{'n_estimators':range(10,100,10)},cv=10)

In [35]:
RFC_Grid.fit(x_tr,y_tr)

GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': range(10, 100, 10)})

In [36]:
RFC_Grid.best_params_

{'n_estimators': 90}

In [37]:
RFC_Grid.best_score_

0.9957396149949342

In [38]:
print(classification_report(y_val,RFC_Grid.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00        16
           6       1.00      1.00      1.00        17
           7       1.00      1.00      1.00        16
           8       0.88      1.00      0.93        21
           9       1.00      1.00      1.00        15
          10       0.90      1.00      0.95         9
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        15
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        12
          16       1.00      1.00      1.00        11
          17       1.00      1.00      1.00        18
          18       1.00      1.00      1.00        17
          19       1.00      1.00      1.00        15
          20       1.00      0.82      0.90        17
          21       1.00      1.00      1.00        20

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [39]:
y_pred = RFC_Grid.predict(x_test)

In [40]:
y_pred = RFC_Grid.predict(x_val)

In [41]:
y_pred

array([15, 12, 20, 21, 13,  1,  8, 21, 14, 13,  0, 17, 17, 11,  4,  1, 11,
        5, 14,  9, 21,  4,  9,  8,  7, 20,  0,  7,  9, 14,  3,  1,  0,  2,
       15,  6,  1, 15,  8,  2,  2,  0, 14,  2, 11, 12, 21,  1,  4,  0, 11,
       11, 19, 10, 15, 12, 19,  5, 18,  3,  7,  4,  9,  5, 11, 14,  6, 11,
       21, 14,  8, 14, 18, 11,  3, 17, 17, 19, 14, 18,  6, 19, 15, 20, 17,
       19,  1,  5, 11, 21,  8,  5,  8, 18, 20, 13,  9, 16, 13, 14, 17, 13,
       17, 10,  4, 21,  9, 14, 17,  0, 16, 14,  0, 19,  1, 12,  7,  8,  9,
        8, 15,  8, 10,  2, 20, 10,  7, 13, 18,  6, 14,  3, 19, 20,  9, 14,
        8, 20,  2,  0, 13, 20, 11,  5,  0,  9, 18,  7, 20, 15,  6,  6,  4,
        4, 13, 20,  8, 19,  0,  6, 10, 16,  7,  8, 12, 12, 20, 17, 20, 18,
       19, 16,  7, 18,  6, 10, 15,  1, 16, 19,  6,  3,  8,  2, 11,  2, 13,
        8,  8,  7,  3, 18,  5,  4, 13, 17,  8, 10, 15,  5, 21, 16, 14,  5,
        0,  8,  6,  7,  1,  3, 21,  3, 11, 18,  4,  1,  1, 17,  9,  5, 12,
       19,  3, 17, 19,  8,  2,  6, 17, 14, 17,  8, 21,  3, 18,  5, 14, 21,
       12,  9,  7, 14, 11, 20,  4, 19,  6,  7, 21,  9, 10,  0,  5, 17,  6,
        8,  8, 17,  3, 12,  2,  2, 13,  0, 21, 11, 20, 12, 11,  6,  4, 11,
       12,  4, 11,  6,  7,  1, 16, 16, 21,  1, 21,  2, 11,  0,  5,  5, 18,
        3,  6,  4,  9,  2, 13,  7, 10,  7,  8,  5,  9, 18, 16,  2, 18, 19,
        9, 21, 21, 12, 18,  8,  3, 10, 21, 11, 13,  6, 11, 12, 21, 19, 16,
        0,  2, 14, 17,  2,  0, 14, 21, 15, 12,  0,  2, 12, 15,  2, 16, 14,
        8,  3,  3, 17, 11,  5, 13,  7, 18, 18, 15, 13])

In [42]:
y_pred

array([15, 12, 20, 21, 13,  1,  8, 21, 14, 13,  0, 17, 17, 11,  4,  1, 11,
        5, 14,  9, 21,  4,  9,  8,  7, 20,  0,  7,  9, 14,  3,  1,  0,  2,
       15,  6,  1, 15,  8,  2,  2,  0, 14,  2, 11, 12, 21,  1,  4,  0, 11,
       11, 19, 10, 15, 12, 19,  5, 18,  3,  7,  4,  9,  5, 11, 14,  6, 11,
       21, 14,  8, 14, 18, 11,  3, 17, 17, 19, 14, 18,  6, 19, 15, 20, 17,
       19,  1,  5, 11, 21,  8,  5,  8, 18, 20, 13,  9, 16, 13, 14, 17, 13,
       17, 10,  4, 21,  9, 14, 17,  0, 16, 14,  0, 19,  1, 12,  7,  8,  9,
        8, 15,  8, 10,  2, 20, 10,  7, 13, 18,  6, 14,  3, 19, 20,  9, 14,
        8, 20,  2,  0, 13, 20, 11,  5,  0,  9, 18,  7, 20, 15,  6,  6,  4,
        4, 13, 20,  8, 19,  0,  6, 10, 16,  7,  8, 12, 12, 20, 17, 20, 18,
       19, 16,  7, 18,  6, 10, 15,  1, 16, 19,  6,  3,  8,  2, 11,  2, 13,
        8,  8,  7,  3, 18,  5,  4, 13, 17,  8, 10, 15,  5, 21, 16, 14,  5,
        0,  8,  6,  7,  1,  3, 21,  3, 11, 18,  4,  1,  1, 17,  9,  5, 12,
       19,  3, 17, 19,  8,  2,  6, 17, 14, 17,  8, 21,  3, 18,  5, 14, 21,
       12,  9,  7, 14, 11, 20,  4, 19,  6,  7, 21,  9, 10,  0,  5, 17,  6,
        8,  8, 17,  3, 12,  2,  2, 13,  0, 21, 11, 20, 12, 11,  6,  4, 11,
       12,  4, 11,  6,  7,  1, 16, 16, 21,  1, 21,  2, 11,  0,  5,  5, 18,
        3,  6,  4,  9,  2, 13,  7, 10,  7,  8,  5,  9, 18, 16,  2, 18, 19,
        9, 21, 21, 12, 18,  8,  3, 10, 21, 11, 13,  6, 11, 12, 21, 19, 16,
        0,  2, 14, 17,  2,  0, 14, 21, 15, 12,  0,  2, 12, 15,  2, 16, 14,
        8,  3,  3, 17, 11,  5, 13,  7, 18, 18, 15, 13])

## Here we Saved Model as pkl file

In [43]:
import joblib

In [44]:
joblib.dump(RFC_Grid,'crop.pkl')

['crop.pkl']

## Here we Trying to the Device Version to use it in requirements.txt

In [45]:
(np.__version__)

'1.26.4'

In [46]:
(joblib.__version__)

'1.2.0'