## Import Important Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import  StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report , roc_auc_score , f1_score , precision_score , recall_score , mean_squared_error , r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from imblearn.over_sampling import SMOTE
import joblib
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV

In [2]:
crop = pd.read_csv(r'C:\Users\Hamada\Downloads\archive (14)\Crop_recommendation.csv')
crop.head(5)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [4]:
crop.duplicated().sum()

0

In [5]:
crop.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
crop.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [7]:
crop['label'] = LabelEncoder().fit_transform(crop['label'])

In [8]:
crop.head(5)

    N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536     20
1  85  58  41    21.770462  80.319644  7.038096  226.655537     20
2  60  55  44    23.004459  82.320763  7.840207  263.964248     20
3  74  35  40    26.491096  80.158363  6.980401  242.864034     20
4  78  42  42    20.130175  81.604873  7.628473  262.717340     20

In [9]:
x = crop.drop('label',axis=1)
y = crop['label']

In [10]:
y.value_counts(normalize=True)

label
20    0.045455
11    0.045455
8     0.045455
6     0.045455
4     0.045455
17    0.045455
16    0.045455
0     0.045455
15    0.045455
21    0.045455
7     0.045455
12    0.045455
1     0.045455
19    0.045455
10    0.045455
2     0.045455
14    0.045455
13    0.045455
18    0.045455
9     0.045455
3     0.045455
5     0.045455
Name: proportion, dtype: float64

In [11]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [12]:
x_tr , x_val , y_tr , y_val = train_test_split(x_train,y_train,test_size=0.2)

In [13]:
std = StandardScaler()

x_tr = std.fit_transform(x_tr)
x_val = std.transform(x_val)
x_test = std.transform(x_test)

In [14]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(x_tr,y_tr)
dt.score(x_val,y_val)

0.9829545454545454

In [15]:
print(classification_report(y_val,dt.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       0.94      0.85      0.89        20
           9       1.00      1.00      1.00        14
          10       0.94      1.00      0.97        17
          11       1.00      0.93      0.97        15
          12       1.00      1.00      1.00        21
          13       1.00      0.94      0.97        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      1.00      1.00        16
          17       0.92      1.00      0.96        11
          18       1.00      1.00      1.00        15
          19       1.00      1.00      1.00        22
          20       0.89      0.94      0.92        18
          21       1.00      1.00      1.00        12

    accuracy                           0.98       352
   macro avg       0.98      0.98      0.98       352
weighted avg       0.98      0.98      0.98       352

In [16]:
rfc = RandomForestClassifier()
rfc.fit(x_tr,y_tr)
rfc.score(x_val,y_val)

0.9943181818181818

In [17]:
print(classification_report(y_val,rfc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       1.00      0.95      0.97        20
           9       1.00      1.00      1.00        14
          10       1.00      1.00      1.00        17
          11       1.00      0.93      0.97        15
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      1.00      1.00        16
          17       1.00      1.00      1.00        11
          18       1.00      1.00      1.00        15
          19       1.00      1.00      1.00        22
          20       0.95      1.00      0.97        18
          21       1.00      1.00      1.00        12

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [18]:
lin_svc = SVC(kernel='linear')
lin_svc.fit(x_tr,y_tr)
lin_svc.score(x_val,y_val)

0.9886363636363636

In [19]:
print(classification_report(y_val,lin_svc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       0.91      1.00      0.95        20
           9       0.93      1.00      0.97        14
          10       1.00      1.00      1.00        17
          11       1.00      0.93      0.97        15
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      1.00      1.00        16
          17       1.00      1.00      1.00        11
          18       1.00      0.93      0.97        15
          19       1.00      1.00      1.00        22
          20       1.00      0.89      0.94        18
          21       1.00      1.00      1.00        12

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [20]:
poly_svc = SVC(kernel='poly')
poly_svc.fit(x_tr,y_tr)
poly_svc.score(x_val,y_val)

0.9176136363636364

In [21]:
print(classification_report(y_val,poly_svc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.94      0.97        17
           2       1.00      0.78      0.88        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      0.64      0.78        14
           6       1.00      1.00      1.00        16
           7       1.00      1.00      1.00         9
           8       0.89      0.80      0.84        20
           9       1.00      1.00      1.00        14
          10       0.84      0.94      0.89        17
          11       0.42      1.00      0.59        15
          12       0.95      0.95      0.95        21
          13       1.00      0.88      0.93        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      0.88      0.93        16
          17       1.00      0.82      0.90        11
          18       1.00      0.73      0.85        15
          19       0.92      1.00      0.96        22
          20       1.00      0.89      0.94        18
          21       1.00      1.00      1.00        12

    accuracy                           0.92       352
   macro avg       0.96      0.92      0.93       352
weighted avg       0.95      0.92      0.93       352

In [22]:
poly_svc = SVC(kernel='rbf')
poly_svc.fit(x_tr,y_tr)
poly_svc.score(x_val,y_val)

0.9886363636363636

In [23]:
print(classification_report(y_val,poly_svc.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       1.00      0.96      0.98        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       0.95      1.00      0.98        20
           9       0.93      1.00      0.97        14
          10       0.94      1.00      0.97        17
          11       1.00      0.93      0.97        15
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      1.00      1.00        16
          17       1.00      1.00      1.00        11
          18       1.00      0.93      0.97        15
          19       1.00      1.00      1.00        22
          20       1.00      0.94      0.97        18
          21       1.00      1.00      1.00        12

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [24]:
naive = GaussianNB()
naive.fit(x_tr,y_tr)
naive.score(x_val,y_val)

0.9971590909090909

In [25]:
print(classification_report(y_val,naive.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       1.00      1.00      1.00        20
           9       1.00      1.00      1.00        14
          10       1.00      1.00      1.00        17
          11       1.00      0.93      0.97        15
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      1.00      1.00        16
          17       1.00      1.00      1.00        11
          18       1.00      1.00      1.00        15
          19       1.00      1.00      1.00        22
          20       1.00      1.00      1.00        18
          21       1.00      1.00      1.00        12

    accuracy                           1.00       352
   macro avg       1.00      1.00      1.00       352
weighted avg       1.00      1.00      1.00       352

In [26]:
KNN = KNeighborsClassifier(n_neighbors=20)
KNN.fit(x_tr,y_tr)
KNN.score(x_val,y_val)

0.9460227272727273

In [27]:
print(classification_report(y_val,KNN.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       0.91      0.91      0.91        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       0.91      1.00      0.95        20
           9       0.82      1.00      0.90        14
          10       0.85      1.00      0.92        17
          11       1.00      0.93      0.97        15
          12       0.95      1.00      0.98        21
          13       0.93      0.81      0.87        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      0.62      0.77        16
          17       1.00      1.00      1.00        11
          18       1.00      0.67      0.80        15
          19       0.79      1.00      0.88        22
          20       1.00      0.89      0.94        18
          21       1.00      1.00      1.00        12

    accuracy                           0.95       352
   macro avg       0.96      0.95      0.95       352
weighted avg       0.95      0.95      0.94       352

In [28]:
Log = LogisticRegression()
Log.fit(x_tr,y_tr)
Log.score(x_val,y_val)

0.9744318181818182

In [29]:
print(mean_squared_error(y_val,Log.predict(x_val)))
print(r2_score(y_val,Log.predict(x_val)))

2.1704545454545454
0.9469241619518822

In [30]:
linear = LinearRegression()
linear.fit(x_tr,y_tr)
linear.score(x_val,y_val)

0.3142634435698901

In [31]:
print(mean_squared_error(y_val,linear.predict(x_val)))
print(r2_score(y_val,linear.predict(x_val)))

28.042138958573858
0.3142634435698901

In [32]:
RFC_Grid = GridSearchCV(RandomForestClassifier(),{'n_estimators':range(10,100,10)},cv=10)

In [33]:
RFC_Grid.fit(x_tr,y_tr)

GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': range(10, 100, 10)})

In [34]:
RFC_Grid.best_params_

{'n_estimators': 70}

In [35]:
RFC_Grid.best_score_

0.997872340425532

In [36]:
print(classification_report(y_val,RFC_Grid.predict(x_val)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00        14
           5       1.00      1.00      1.00        14
           6       0.94      1.00      0.97        16
           7       1.00      1.00      1.00         9
           8       1.00      0.95      0.97        20
           9       1.00      1.00      1.00        14
          10       1.00      1.00      1.00        17
          11       1.00      0.93      0.97        15
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        16
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        14
          16       1.00      1.00      1.00        16
          17       1.00      1.00      1.00        11
          18       1.00      1.00      1.00        15
          19       1.00      1.00      1.00        22
          20       0.95      1.00      0.97        18
          21       1.00      1.00      1.00        12

    accuracy                           0.99       352
   macro avg       0.99      0.99      0.99       352
weighted avg       0.99      0.99      0.99       352

In [37]:
y_pred = RFC_Grid.predict(x_test)

In [43]:
y_pred = RFC_Grid.predict(x_val)

In [44]:
y_pred

array([ 3,  1, 16,  3,  6,  8,  2,  7, 21,  6, 18,  9, 10,  1, 18,  6, 17,
        5, 18,  8, 20,  6, 12, 14,  8, 20,  8, 19,  4, 14,  0, 14, 16, 18,
       11, 12,  5, 11,  5,  9, 10, 13,  4,  7,  8, 18, 17,  4, 18, 13, 17,
       12,  2,  4, 16, 16, 10,  5,  8, 20,  7, 17,  0,  2,  7, 13, 19, 12,
       10, 13,  6, 21,  2,  0, 21,  1,  7, 15, 13,  5,  2, 15,  6, 19, 21,
       13, 12,  1, 15, 19, 19, 14,  3,  2, 14, 19, 13, 15, 15,  6,  4, 21,
        9,  0,  3, 18, 20, 19,  6, 12,  9, 20, 17,  8, 19, 11,  4,  1,  2,
       19,  4,  0, 11, 12, 13, 13, 12,  6,  5, 19, 14,  8,  3, 20,  0, 20,
       10,  1, 16, 21, 18,  3, 18,  5,  5, 10, 20, 17,  3, 16, 11, 12, 12,
        3,  5, 12,  2, 13, 16,  8, 20, 19,  2,  1,  1,  8,  5, 14, 10, 16,
       21, 16, 13, 12, 10,  1,  8,  5,  6, 15, 20, 20, 13, 20, 17, 12,  3,
        9,  4, 11, 21, 10,  9, 20, 17,  2,  1, 19,  4, 16,  0, 15,  8,  9,
        4,  2,  1, 14,  5,  2,  1,  9,  8,  9, 20, 12,  7,  0,  3, 15,  1,
       15,  6,  2,  9, 13,  2,  2, 16, 10, 16,  7, 17, 19,  0,  4,  8, 21,
        1, 20,  6, 12, 14,  4,  8,  8, 19,  0,  2, 14, 11, 11, 15, 18,  0,
       15, 15, 15,  1, 11, 12, 15,  0, 17, 17, 18,  4,  5,  0, 20, 16,  9,
        6,  0, 18, 18, 10, 19, 16, 20, 14, 20, 19,  6, 21, 19,  0, 11, 10,
       14, 10,  9,  0,  1, 20, 10, 19, 14,  6,  8,  0, 14, 19,  8, 12, 11,
       18,  4, 10, 19, 12,  2,  3,  3, 10, 14, 10,  9,  7,  6, 13, 14,  2,
        2,  3, 13, 12, 11,  2, 21, 16, 18, 14, 14, 13,  9, 12,  2, 11, 21,
        7,  1,  8,  5,  2, 19, 12,  2, 19, 11, 16,  6])

In [38]:
y_pred

array([11, 15, 16, 17,  2,  1,  4, 18,  5, 19, 16,  0, 12, 11,  4,  4, 15,
       20, 10,  8,  4,  8, 16,  7, 20,  2, 14, 19,  1, 14,  8, 10,  4, 19,
        4,  6, 20, 14,  8, 14, 20, 17, 14,  6, 12,  1,  9,  3,  2,  5,  6,
        7, 18, 10,  8, 19,  8, 19, 15,  9, 20,  7,  2,  4,  5, 10,  7,  4,
        2, 13, 20,  3, 11, 12,  9,  0, 19, 15,  8,  4, 15, 17, 18, 21, 20,
       16,  0, 21, 16, 17,  3, 11,  1,  6, 20,  5,  9,  5,  1, 11,  6, 21,
        6,  8, 18, 13, 20, 11,  7, 19,  7, 13,  4,  4,  3,  5, 10,  2, 16,
       14, 21,  1, 19, 11, 18,  5, 16, 20, 19,  8, 19,  4,  1, 13,  2,  7,
       10, 12,  7, 17,  1,  3,  4, 20,  8,  3,  5, 17,  9, 12,  6, 18, 11,
       10,  0, 17,  6,  8,  3, 18, 11, 19, 14, 19, 16, 12,  7, 16, 10, 21,
       18,  9, 16,  7,  1,  3,  8, 16,  0, 12, 12,  8, 12, 14, 10,  0,  6,
        9, 20, 10, 19,  8, 13, 15,  1,  5, 13,  2, 19,  7,  7, 11, 10,  3,
        7, 10,  3, 13, 14,  4,  4, 11, 14, 19, 14,  8,  6,  4, 20, 14, 18,
        8, 20, 15, 16, 10,  8, 13, 18, 15,  8,  5, 11,  0, 16,  3,  8, 11,
        8, 14, 19, 16,  0,  6, 15,  8, 12,  5,  1, 17, 16, 17, 15, 11, 16,
       11,  5,  2, 14, 16,  7, 14, 15, 11,  9,  5, 17, 11, 20, 13,  7,  2,
       17, 13, 14, 18,  1,  2, 12, 13,  9, 16, 10, 15, 20,  7, 19, 16,  3,
        9, 19,  1, 17, 13, 12, 15, 16, 19,  6, 17,  7,  5, 16,  5, 17, 12,
        1, 16,  3,  8, 14,  5, 17, 11, 11, 10, 19, 20,  1,  8,  1,  0,  1,
        4,  8,  4, 14, 19, 17, 19, 12, 11,  8,  2,  7, 10,  7, 14, 16,  2,
       14,  5, 15, 12, 16,  4, 11,  5, 14,  8, 17, 10,  6, 19,  5,  2,  8,
        0,  1,  4,  4,  7,  3, 15, 14,  6,  3,  4, 21, 12,  7, 12, 19,  5,
        0,  0, 10, 10, 20, 16, 14,  1,  8, 15,  2,  1,  6,  3,  3,  1,  4,
       15, 12, 11,  5, 20,  0,  4,  6,  4,  8,  1,  7,  3, 21, 11, 16, 14,
       16, 18,  4, 16,  3, 18, 14,  7,  6,  5, 17, 20,  4, 21,  2,  0, 10,
       13, 11,  8,  0,  7, 20, 17,  7, 10, 12, 18, 18, 11,  6, 17])

In [40]:
import joblib

In [41]:
joblib.dump(RFC_Grid,'crop.pkl')

['crop.pkl']